language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  # - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2.2.1

gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile

matrix:
  allow_failures:
    - rvm: rbx-2.2.1
    - rvm: jruby-19mode
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: rbx-2.2.1
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: rbx-2.2.1
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: rbx-2.2.1
      gemfile: gemfiles/rails_4.1.gemfile
